const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
function app(saved,userAgent=''){
  const nodes=new Map();const timers=new Map();let timerId=0;const stored=new Map(saved?[['malssum_dictation_v3',saved]]:[]);
  const node=()=>({textContent:'',style:{setProperty(){}},classList:{toggle(){}},append(){},replaceChildren(){},scrollIntoView(options){this.scrolled=options;},showModal(){},close(){}});
  const document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},createElement:node,documentElement:node(),addEventListener(){}};
  class Speech{constructor(){Speech.last=this;this.results=[];this.lastKey=null;}start(){this.onstart?.();}abort(){}}
  const context=vm.createContext({document,navigator:{userAgent},window:{SpeechRecognition:Speech,addEventListener(){}},Option:function(){},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},setTimeout:(f,ms)=>{timers.set(++timerId,{f,ms});return timerId;},clearTimeout:id=>timers.delete(id),Date,Map,console,matchMedia:()=>({matches:true})});
  vm.runInContext(fs.readFileSync('public/bible-data.js','utf8')+fs.readFileSync('public/reader.js','utf8')+fs.readFileSync('public/backup.js','utf8'),context);
  return {run:code=>vm.runInContext(code,context),nodes,stored,Speech,advance:ms=>{for(const[id,t]of [...timers])if(t.ms===ms){timers.delete(id);t.f();}},say:(text,final=true)=>{const r=[{transcript:text}];r.isFinal=final;const speech=Speech.last;const key=vm.runInContext('verseKey()',context);if(speech.lastKey!==key){speech.results.push(r);speech.lastKey=key;}else speech.results[speech.results.length-1]=r;speech.onresult({results:speech.results,resultIndex:speech.results.length-1});}};
}
test('silence never counts; inaccurate dictation is retained and advances after pause',()=>{const a=app();a.run('start()');a.advance(1000);assert.equal(a.run('todayEntries().length'),0);a.say('잘못 들린 인물 이름');assert.equal(a.run('todayEntries().length'),0);a.advance(1000);assert.equal(a.run('todayEntries().length'),1);assert.equal(a.run('state.entries.gen_1_1.text'),'잘못 들린 인물 이름');assert.equal(a.run('state.index'),1);});
test('interim results do not count; repeated final events are not duplicated',()=>{const a=app();a.run('start()');a.say('미완성',false);a.advance(1000);assert.equal(a.run('todayEntries().length'),0);a.say('받아쓴 내용');a.say('받아쓴 내용');assert.equal(a.run('entry().text'),'받아쓴 내용');a.run('complete();complete()');assert.equal(a.run('todayEntries().length'),1);});
test('stopping and changing chapter cancel pending completion and old events',()=>{const a=app();a.run('start()');a.say('첫 절');const late=a.Speech.last.onresult;a.run('navigate(1)');a.advance(1000);const r=[{transcript:'늦게 온 결과'}];r.isFinal=true;late({results:[r]});assert.equal(a.run('todayEntries().length'),0);assert.equal(a.run('state.chapter'),2);});
test('records survive reload; old completed verses cannot count twice',()=>{const a=app();a.run('start()');a.say('내 목소리');a.run('complete()');const b=app(a.stored.get('malssum_dictation_v3'));assert.equal(b.run('todayEntries().length'),1);b.run('state.index=0;complete()');assert.equal(b.run('todayEntries().length'),1);});
test('unsupported chapters have no fabricated verses and cannot start',()=>{const a=app();a.run("state.book='rev';state.chapter=23;render();start()");assert.equal(a.run('verses().length'),0);assert.equal(a.run('listening'),false);assert.equal(a.nodes.get('mic').disabled,true);});
test('permission errors release listening state and preserve drafts',()=>{const a=app();a.run('start()');a.say('저장된 내용');a.Speech.last.onerror({error:'not-allowed'});assert.equal(a.run('listening'),false);assert.equal(a.run('entry().text'),'저장된 내용');a.advance(1000);assert.equal(a.run('todayEntries().length'),0);});

test('overall progress includes earlier days, deduplicates verses and excludes drafts',()=>{const a=app();a.run(`state.entries={a:{book:'gen',chapter:1,verse:1,text:'읽음',completed:true,date:'2020-01-01'},b:{book:'gen',chapter:1,verse:2,text:'오늘',completed:true,date:dateKey()},duplicate:{book:'gen',chapter:1,verse:1,text:'중복',completed:true},draft:{book:'gen',chapter:1,verse:3,text:'초안',completed:false}}`);assert.equal(a.run('overallProgress().count'),2);assert.equal(a.run('todayEntries().length'),1);assert.equal(a.run('overallProgress().label'),'< 0.01%');assert.match(a.run('shareText(captureShare())'),/누적 2 \/ 31,102절/);});
test('sharing uses native share with a prepared image and handles cancellation',async()=>{const a=app();a.run(`navigator={canShare:()=>true,share:async data=>{navigator.sent=data}};shareFile={name:'record.png'}`);await a.run('shareToKakao()');assert.equal(a.run('navigator.sent.files[0].name'),'record.png');assert.equal(a.run('navigator.sent.url'),undefined);a.run(`navigator.share=async()=>{throw {name:'AbortError'}}`);await a.run('shareToKakao()');assert.match(a.nodes.get('share-message').textContent,/취소/);});
test('unsupported share offers alternatives and clipboard failure exposes selectable text',async()=>{const a=app();a.run('navigator={}');await a.run('shareToKakao()');assert.match(a.nodes.get('share-message').textContent,/지원하지/);a.nodes.set('share-copy-text',{select(){}});await a.run('copyShare()');assert.equal(a.nodes.get('share-copy-text').hidden,false);assert.match(a.nodes.get('share-copy-text').value,/성경 전체 진도/);});

test('backup round trip restores completed verses, draft, position and plan on another device',()=>{
  const a=app();a.run('start()');a.say('첫 절 받아쓰기');a.run('complete()');a.say('둘째 절 초안');a.run("state.plan='3years';state.pause=1000");
  const exported=a.run('JSON.stringify(backupPayload())');
  const b=app();b.run(`pendingRestore=validateBackup(JSON.parse(${JSON.stringify(exported)}));restoreBackup()`);
  assert.equal(b.run('todayEntries().length'),1);assert.equal(b.run('state.entries.gen_1_2.text'),'둘째 절 초안');assert.equal(b.run('state.index'),1);assert.equal(b.run('state.plan'),'3years');
  const c=app(b.stored.get('malssum_dictation_v3'));assert.equal(c.run('state.entries.gen_1_1.text'),'첫 절 받아쓰기');
});
test('restore merges and is idempotent; an old backup cannot remove newer local records',()=>{
  const a=app();a.run('start()');a.say('첫 절');a.run('complete();globalThis.oldBackup=backupPayload()');a.say('새 기록');a.run('complete();pendingRestore=validateBackup(oldBackup);restoreBackup()');
  assert.equal(a.run('todayEntries().length'),2);a.run('pendingRestore=validateBackup(oldBackup);restoreBackup()');assert.equal(a.run('todayEntries().length'),2);
});
test('damaged, future-version, impossible-date and malicious backup keys are rejected',()=>{
  const a=app();a.run('start()');a.say('기록');a.run('complete()');
  for(const mutation of ["b.version=2", "b.state.entries.gen_1_1.date='2026-02-31'", "b.state.entries.constructor={}", "b.state.chapter=999", "b.state.entries.gen_1_1.verse=4"]){assert.throws(()=>a.run(`{const b=backupPayload();${mutation};validateBackup(b)}`));}
  assert.equal(a.run('todayEntries().length'),1);
});
test('storage failure leaves current state unchanged on restore',()=>{
  const a=app();a.run("pendingRestore={...state,plan:'3years'};localStorage.setItem=()=>{throw new Error('quota')};restoreBackup()");
  assert.equal(a.run('state.plan'),'1year');assert.match(a.nodes.get('backup-message').textContent,/현재 기록은 유지/);
});

test('microphone permission grants release the probe and start recognition',async()=>{const a=app();a.run(`window.isSecureContext=true;globalThis.released=0;navigator={mediaDevices:{getUserMedia:async options=>{if(!options.audio)throw Error('audio required');return {getTracks:()=>[{stop(){released++}}]}}}}`);await a.nodes.get('mic').onclick();assert.equal(a.run('released'),1);assert.equal(a.run('listening'),true);});
test('HTTP and denied microphone permission do not start recognition',async()=>{const a=app();a.run('window.isSecureContext=false');await a.nodes.get('mic').onclick();assert.match(a.nodes.get('status').textContent,/HTTPS/);assert.equal(a.Speech.last,undefined);a.run(`window.isSecureContext=true;navigator={mediaDevices:{getUserMedia:async()=>{throw {name:'NotAllowedError'}}}}`);await a.nodes.get('mic').onclick();assert.equal(a.run('listening||starting'),false);assert.match(a.nodes.get('hint').textContent,/사이트 설정/);});
test('late microphone grant after cancellation or navigation is released without starting',async()=>{for(const action of ['stop()','navigate(1)']){const a=app();a.run(`navigator={mediaDevices:{getUserMedia:()=>new Promise(resolve=>{globalThis.grant=resolve})}};globalThis.released=0`);const pending=a.nodes.get('mic').onclick();a.run(action);a.run('grant({getTracks:()=>[{stop(){released++}}]})');await pending;assert.equal(a.run('released'),1);assert.equal(a.run('listening||starting'),false);assert.equal(a.Speech.last,undefined);}});

test('page entry requests microphone permission without starting dictation',async()=>{const a=app();a.run(`globalThis.requests=0;globalThis.released=0;navigator={mediaDevices:{getUserMedia:async()=>{requests++;return {getTracks:()=>[{stop(){released++}}]}}}}`);a.advance(0);await Promise.resolve();assert.equal(a.run('requests'),1);assert.equal(a.run('released'),1);assert.equal(a.run('listening||starting'),false);assert.equal(a.Speech.last,undefined);assert.match(a.nodes.get('status').textContent,/준비/);});

test('30-day calendar handles start, last day, expiry and leap day',()=>{const a=app();assert.equal(a.run("READING_PLANS['30days'].dailyTargetVerses"),1036);assert.equal(a.run("planCalendar('2026-09-24','2026-09-24','30days').remaining"),30);assert.equal(a.run("planCalendar('2026-09-24','2026-09-24','30days').elapsed"),0);assert.equal(a.run("planCalendar('2026-09-24','2026-10-23','30days').remaining"),1);assert.equal(a.run("planCalendar('2026-09-24','2026-10-24','30days').remaining"),0);assert.equal(a.run("planCalendar('2028-02-28','2028-03-01','30days').elapsed"),2);});
test('100-day course uses 312 verses and ends on day 100',()=>{const a=app();assert.equal(a.run("READING_PLANS['100days'].dailyTargetVerses"),312);assert.equal(a.run("planCalendar('2026-09-26','2026-09-26','100days').remaining"),100);assert.equal(a.run("planCalendar('2026-09-26','2027-01-03','100days').remaining"),1);assert.equal(a.run("planCalendar('2026-09-26','2027-01-04','100days').remaining"),0);});
test('daily goal stops once, saves next verse, resumes without counting twice',()=>{const a=app();a.run(`state.plan='3years';for(let v=2;v<=29;v++)state.entries['gen_1_'+v]={text:'읽음',completed:true,book:'gen',chapter:1,verse:v,date:dateKey()};start()`);a.say('오늘 마지막 분량');a.run('complete()');assert.equal(a.run('todayEntries().length'),29);assert.equal(a.run('listening'),false);assert.equal(a.run('state.index'),29);assert.equal(a.nodes.get('daily-complete').hidden,false);const b=app(a.stored.get('malssum_dictation_v3'));assert.equal(b.run('state.index'),29);b.run('start()');b.say('더 읽기');b.run('complete()');assert.equal(b.run('todayEntries().length'),30);assert.equal(b.run('listening'),true);});
test('chapter end stores next chapter and yesterday completion does not show daily banner',()=>{const a=app();a.run("state.index=30;start()");a.say('마지막 절');a.run('complete()');assert.equal(a.run('state.chapter'),2);assert.equal(a.run('state.index'),0);const b=app(a.stored.get('malssum_dictation_v3'));assert.equal(b.run('state.chapter'),2);b.run("for(const e of Object.values(state.entries))e.date='2020-01-01';updateTotals()");assert.equal(b.nodes.get('daily-complete').hidden,true);});
test('chapter transition and recognition start keep the active first verse in view',()=>{const a=app();a.run("state.index=30;start()");a.say('마지막 절');a.run('complete()');assert.equal(a.run('state.chapter'),2);assert.equal(a.nodes.get('verse-0').scrolled?.block,'center');a.nodes.get('verse-0').scrolled=null;a.run('start()');assert.equal(a.nodes.get('verse-0').scrolled?.block,'center');});
test('plan start date and 30-day course survive backup restore; older backups still load',()=>{const a=app();a.run("state.plan='30days';state.planStart='2026-09-01';globalThis.b=backupPayload()");assert.equal(a.run('validateBackup(b).planStart'),'2026-09-01');assert.equal(a.run('validateBackup(b).plan'),'30days');a.run('delete b.state.planStart');assert.equal(a.run('validPlanDate(validateBackup(b).planStart)'),true);a.run("b.state.planStart='2026-02-31'");assert.throws(()=>a.run('validateBackup(b)'));});


test('complete Bible has 66 books and every chapter with stable verse numbers',()=>{const a=app();assert.equal(a.run('BIBLE_BOOKS.length'),66);assert.equal(a.run('Object.keys(CHAPTER_DATA).length'),1189);assert.equal(a.run('Object.values(CHAPTER_DATA).reduce((n,v)=>n+v.length,0)'),31102);assert.equal(a.run('CHAPTER_DATA.rev_22.length'),21);assert.match(a.run('CHAPTER_DATA.gen_35[21]'),/아들은 열둘이라/);assert.match(a.run('CHAPTER_DATA.exo_1[0]'),/야곱/);});
test('combined verses display once and completion advances past the range without double counting',()=>{const a=app();a.run("state.book='deu';state.chapter=6;state.index=17;render();start()");a.say('합쳐진 절 낭독');a.run('complete()');assert.equal(a.run('todayEntries().length'),2);assert.equal(a.run('state.index'),19);assert.equal(a.run('state.entries.deu_6_19.verse'),19);a.run('state.index=18;render()');assert.equal(a.run('state.index'),17);a.run('complete()');assert.equal(a.run('todayEntries().length'),2);});

function speechSnapshot(recognizer,texts,from=0){const results=texts.map(value=>{const r=[{transcript:typeof value==='string'?value:value.text}];r.isFinal=typeof value==='string'||value.final;return r;});recognizer.onresult({results,resultIndex:from});}
test('mobile cumulative final slots do not repeat the opening phrase',()=>{const a=app();a.run('start()');const r=a.Speech.last;speechSnapshot(r,['태초에']);speechSnapshot(r,['태초에','태초에'],1);speechSnapshot(r,['태초에','태초에','태초에 하나님이'],2);speechSnapshot(r,['태초에','태초에','태초에 하나님이','천지를 창조하시니라'],3);assert.equal(a.run('entry().text'),'태초에 하나님이 천지를 창조하시니라');});
test('real repeated words and separate speech segments remain intact',()=>{const a=app();a.run('start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['거룩 거룩']);r.onspeechend();r.onspeechstart();speechSnapshot(r,['거룩 거룩','거룩 거룩'],1);assert.equal(a.run('entry().text'),'거룩 거룩 거룩 거룩');});
test('verse transitions keep one recognizer and ignore already consumed results',()=>{const a=app();a.run('start()');const r=a.Speech.last;let aborts=0;r.abort=()=>aborts++;speechSnapshot(r,['첫 절']);a.advance(1000);assert.equal(a.run('state.index'),1);assert.equal(a.Speech.last,r);assert.equal(aborts,0);speechSnapshot(r,['첫 절']);assert.equal(a.run('entry()'),undefined);speechSnapshot(r,['첫 절','둘째 절'],1);assert.equal(a.run('entry().text'),'둘째 절');a.advance(1000);assert.equal(a.run('todayEntries().length'),2);assert.equal(a.Speech.last,r);});
test('interim replacement stays provisional and does not duplicate final words',()=>{const a=app();a.run('start()');const r=a.Speech.last;speechSnapshot(r,[{text:'태초에',final:false}]);speechSnapshot(r,[{text:'태초에 하나님이',final:false}]);assert.equal(a.run('entry()'),undefined);speechSnapshot(r,['태초에 하나님이']);assert.equal(a.run('entry().text'),'태초에 하나님이');assert.equal(a.run('interim'),'');});
test('automatic reconnection ignores replay and expired recognizer callbacks',()=>{const a=app();a.run('start()');const r=a.Speech.last;speechSnapshot(r,['태초에 하나님이']);const late=r.onresult;r.onend();a.advance(800);assert.notEqual(a.Speech.last,r);speechSnapshot(a.Speech.last,['태초에 하나님이']);assert.equal(a.run('entry().text'),'태초에 하나님이');speechSnapshot(a.Speech.last,['태초에 하나님이','태초에 하나님이 천지를'],1);assert.equal(a.run('entry().text'),'태초에 하나님이 천지를');const result=[{transcript:'오래된 결과'}];result.isFinal=true;late({results:[result],resultIndex:0});assert.equal(a.run('entry().text'),'태초에 하나님이 천지를');});
test('repeated empty disconnects stop after bounded retries',()=>{const a=app();a.run('start()');a.Speech.last.onend();a.advance(800);a.Speech.last.onend();a.advance(1600);a.Speech.last.onend();assert.equal(a.run('listening'),false);assert.match(a.nodes.get('status').textContent,/반복해서 종료/);});
test('stop cancels a pending reconnection',()=>{const a=app();a.run('start()');const r=a.Speech.last;r.onend();a.run('stop()');a.advance(800);assert.equal(a.Speech.last,r);assert.equal(a.run('listening'),false);});
test('permission granted on entry avoids a second microphone probe on start',async()=>{const a=app();a.run(`globalThis.requests=0;navigator={mediaDevices:{getUserMedia:async()=>{requests++;return {getTracks:()=>[{stop(){}}]}}}}`);await a.run('requestMicrophone(false)');await a.nodes.get('mic').onclick();assert.equal(a.run('requests'),1);assert.equal(a.run('listening'),true);});


test('a final fragment while speech is active cannot advance a verse',()=>{const a=app();a.run('start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['태초에']);a.advance(1000);assert.equal(a.run('state.index'),0);r.onspeechend();a.advance(1000);assert.equal(a.run('state.index'),1);});
test('mobile supports the selected one-second pause and resumed sound cancels completion',()=>{const a=app(undefined,'Mozilla/5.0 (Linux; Android 14) Chrome/140 Mobile');a.run('state.pause=1000;selectors();start()');assert.equal(a.nodes.get('pause').value,1000);const r=a.Speech.last;r.onsoundstart();speechSnapshot(r,['태초에']);a.advance(1000);assert.equal(a.run('state.index'),0);r.onsoundend();r.onsoundstart();a.advance(1000);assert.equal(a.run('state.index'),0);speechSnapshot(r,['태초에 하나님이']);r.onsoundend();a.advance(1000);assert.equal(a.run('state.index'),1);});
test('service disconnection never counts as silence or completes a fragment',()=>{const a=app(undefined,'Android');a.run('start()');const r=a.Speech.last;speechSnapshot(r,['태초에']);r.onend();a.advance(2800);a.advance(1000);assert.equal(a.run('todayEntries().length'),0);a.advance(800);speechSnapshot(a.Speech.last,['태초에']);a.advance(2800);assert.equal(a.run('todayEntries().length'),0);assert.equal(a.run('state.index'),0);});

test('mobile reconnect after verse 10 cannot copy verse 10 into verse 11',()=>{const a=app(undefined,'Android');a.run('state.pause=2800;state.index=9;start()');const r=a.Speech.last;const text='하나님이 뭍을 땅이라 부르시고 모인 물을 바다라 부르시니';r.onspeechstart();speechSnapshot(r,[text]);r.onspeechend();a.advance(2800);assert.equal(a.run('state.index'),10);r.onend();a.advance(800);const resumed=a.Speech.last;resumed.onspeechstart();speechSnapshot(resumed,[text]);resumed.onspeechend();a.advance(2800);assert.equal(a.run('state.index'),10);assert.equal(a.run('state.entries.gen_1_11'),undefined);assert.equal(a.run('todayEntries().length'),1);resumed.onspeechstart();speechSnapshot(resumed,[text,'하나님이 이르시되 땅은 풀과 씨 맺는 채소를 내라'],1);resumed.onspeechend();a.advance(2800);assert.equal(a.run('state.index'),11);assert.equal(a.run('state.entries.gen_1_11.text'),'하나님이 이르시되 땅은 풀과 씨 맺는 채소를 내라');});

test('replayed text with changed spacing or punctuation is not a new verse',()=>{const a=app(undefined,'Android');a.run('state.pause=2800;state.index=9;start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['하나님이 뭍을 땅이라 부르시고 모인 물을 바다라 부르시니']);r.onspeechend();a.advance(2800);r.onend();a.advance(800);const next=a.Speech.last;next.onspeechstart();speechSnapshot(next,['하나님이뭍을 땅이라 부르시고, 모인 물을 바다라 부르시니.']);next.onspeechend();a.advance(2800);assert.equal(a.run('state.index'),10);assert.equal(a.run('entry()'),undefined);});
test('a result containing old verse followed by new verse keeps only new text',()=>{const a=app(undefined,'Android');a.run('state.pause=2800;state.index=9;start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['뭍을 땅이라 부르시고 물을 바다라 부르시니']);r.onspeechend();a.advance(2800);r.onend();a.advance(800);const next=a.Speech.last;next.onspeechstart();speechSnapshot(next,['뭍을 땅이라 부르시고 물을 바다라 부르시니 하나님이 이르시되 땅은 풀을 내라']);assert.equal(a.run('entry().text'),'하나님이 이르시되 땅은 풀을 내라');});
test('distinct new verse results work without speech-start events while replay is excluded',()=>{const a=app(undefined,'Android');a.run('state.pause=2800;state.index=9;start()');const r=a.Speech.last;speechSnapshot(r,['열 번째 절 내용']);r.onspeechend();a.advance(2800);speechSnapshot(r,['열 번째 절 내용','열 번째 절 내용'],1);r.onspeechend();a.advance(2800);assert.equal(a.run('state.index'),10);assert.equal(a.run('entry()'),undefined);speechSnapshot(r,['열 번째 절 내용','열 번째 절 내용','새롭게 읽은 다음 말씀'],2);r.onspeechend();a.advance(2800);assert.equal(a.run('state.index'),11);assert.equal(a.run('state.entries.gen_1_11.text'),'새롭게 읽은 다음 말씀');});
test('stored unfinished draft cannot auto-complete on speech-end without fresh results',()=>{const a=app(undefined,'Android');a.run("state.entries.gen_1_1={text:'이전 초안',completed:false};start()");a.Speech.last.onspeechstart();a.Speech.last.onspeechend();a.advance(2800);assert.equal(a.run('state.index'),0);assert.equal(a.run('todayEntries().length'),0);});

test('mobile final then speech-end then service-end advances once before reconnect',()=>{const a=app(undefined,'Android');a.run('state.pause=2800;start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['태초에 하나님이 천지를 창조하시니라']);r.onspeechend();r.onend();a.advance(2800);assert.equal(a.run('state.index'),1);assert.equal(a.run('todayEntries().length'),1);const next=a.Speech.last;assert.notEqual(next,r);speechSnapshot(next,['태초에 하나님이 천지를 창조하시니라']);a.advance(2800);assert.equal(a.run('state.index'),1);speechSnapshot(next,['태초에 하나님이 천지를 창조하시니라','땅이 혼돈하고 공허하며'],1);next.onspeechend();next.onend();a.advance(2800);assert.equal(a.run('state.index'),2);assert.equal(a.run('state.entries.gen_1_2.text'),'땅이 혼돈하고 공허하며');});


test('stop or chapter navigation cancels completion waiting after service-end',()=>{for(const action of ['stop()','navigate(1)']){const a=app(undefined,'Android');a.run('start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['첫 절을 읽었어요']);r.onspeechend();r.onend();a.run(action);a.advance(2800);assert.equal(a.run('todayEntries().length'),0);assert.equal(a.run('listening'),false);assert.equal(a.Speech.last,r);}});
test('manual completion during service-end wait reconnects once on next verse',()=>{const a=app(undefined,'Android');a.run('start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['첫 절을 읽었어요']);r.onspeechend();r.onend();a.run('complete()');const resumed=a.Speech.last;assert.notEqual(resumed,r);a.advance(2800);assert.equal(a.Speech.last,resumed);assert.equal(a.run('state.index'),1);assert.equal(a.run('todayEntries().length'),1);});
test('partial interim on service-end cannot complete a verse',()=>{const a=app(undefined,'Android');a.run('start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['읽던 문장',{text:'아직 읽는 중',final:false}]);r.onspeechend();r.onend();a.advance(2800);assert.equal(a.run('state.index'),0);assert.equal(a.run('todayEntries().length'),0);});

test('starting dictation scrolls the saved active verse into view',()=>{const a=app();a.run('state.index=9;render();start()');assert.equal(a.nodes.get('verse-9').scrolled.behavior,'auto');assert.equal(a.nodes.get('verse-9').scrolled.block,'center');assert.match(a.nodes.get('status').textContent,/10절을 듣고/);});
test('half-second and point-eight-second pauses are selectable, saved and restorable',()=>{for(const pause of [500,800]){const a=app();a.run(`state.pause=${pause};selectors();save()`);assert.equal(a.nodes.get('pause').value,pause);const b=app(a.stored.get('malssum_dictation_v3'));assert.equal(b.run('state.pause'),pause);assert.equal(b.run('validateBackup(backupPayload()).pause'),pause);}});
test('half-second pause advances after confirmed speech end',()=>{const a=app(undefined,'Android');a.run('state.pause=500;start()');const r=a.Speech.last;r.onspeechstart();speechSnapshot(r,['한 절을 빠르게 읽음']);r.onspeechend();a.advance(500);assert.equal(a.run('state.index'),1);assert.equal(a.run('todayEntries().length'),1);});
